-- 코드를 입력하세요
# DISTINCT 사용
SELECT COUNT(DISTINCT NAME) AS COUNT FROM ANIMAL_INS 
WHERE NAME IS NOT NULL;

# GROUP BY 사용
#SELECT COUNT(*) AS count
#FROM 
#(
#    SELECT NAME
#    FROM ANIMAL_INS
#    WHERE NAME IS NOT NULL
#    GROUP BY NAME
#) AS UNIQUE_NAME;
