SELECT
  DATE_FORMAT(o.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
  o.PRODUCT_ID,
  o.USER_ID,
  o.SALES_AMOUNT
FROM ONLINE_SALE AS o
WHERE o.SALES_DATE >= DATE('2022-03-01')
  AND o.SALES_DATE <  DATE('2022-04-01')

UNION ALL

SELECT
  DATE_FORMAT(f.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
  f.PRODUCT_ID,
  NULL AS USER_ID,
  f.SALES_AMOUNT
FROM OFFLINE_SALE AS f
WHERE f.SALES_DATE >= DATE('2022-03-01')
  AND f.SALES_DATE <  DATE('2022-04-01')

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;