-- 코드를 입력하세요
SELECT DISTINCT H1.CAR_ID, CASE
WHEN EXISTS(
SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
    WHERE H1.CAR_ID = H2.CAR_ID AND
    '2022-10-16' BETWEEN H2.START_DATE AND H2.END_DATE
) THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H1
ORDER BY H1.CAR_ID DESC;