SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER
        FROM JULY
    ) AS ALL_ORDERS
    GROUP BY FLAVOR
) AS SUM_ORDERS
ORDER BY TOTAL_ORDER DESC
LIMIT 3;
