WITH sub AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) desc
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, date_format(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE join REST_REVIEW
USING(MEMBER_ID)
WHERE MEMBER_ID = (SELECT MEMBER_ID
                   FROM sub)
ORDER BY REVIEW_DATE, REVIEW_TEXT