SELECT SUM(G.SCORE), G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT H 
    JOIN HR_EMPLOYEES E ON H.DEPT_ID = E.DEPT_ID
    JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = '2022'
GROUP BY G.EMP_NO
ORDER BY SUM(G.SCORE) DESC LIMIT 1